### ISSUE TITLE
Please provide armhf builds

### ISSUE THREAD

**Issue by om26er** [OpenPrinting/cups-snap#3]
I need the cups stack on Raspberry Pi running UbuntuCore18, so it would be really helpful if this snap built for armhf as well.

**Comment by Tiger862000** [comment]
Hi, I second om26er's request. Will need the armhf version please. Can you compile for multiple architecture please.

**Comment by pachulo** [comment]
Is there any stopper for this @tillkamppeter ?

**Comment by om26er** [comment]
ping @tillkamppeter, is there a way I could help with the armhf snap ? I have experience with building snaps, however I don't know anything about internals of cups.

**Comment by tillkamppeter** [comment]
I think this is more a question of configuring the builds when putting it up for the Snap Store, but should there be any problems of the Snap not building as armhf version or not running correctly on an armhf I will come back to you.

**Comment by om26er** [comment]
Can you tell about the current plan for putting the printing stack snap into the snap store ? The only reference I found was http://snapcraft.io/printing-stack-snap, which was last updated in 2018.

**Comment by om26er** [comment]
On that topic: I thinking setting this project up for snapcraft.io build service would enable more testing. Hopefully that will just be a few clicks, if you @tillkamppeter think its a good idea.

**Comment by tillkamppeter** [comment]
Yes, I think I will do some thing like snapcraft.io build service, somewhere I also read that the code can be automatically picked up from the GitHub repo. Note that I will also rename the Snap, it will simply be called "cups" and the repo will be called "cups-snap".

**Comment by tillkamppeter** [comment]
I have done the renaming now and also reserved the "cups" name in the Snap Store, and there I have activated the build service, which should trigger a build of the snap on each commit to GitHub. The build service covers the architectures amd64, i386, armhf, arm64, ppc64el, and s390x. So an armhf build should get available soon.

**Comment by om26er** [comment]
Hello again, I don't see the snap `cups` published. It is quite likely the build failed hence it didn't publish to store.

**Comment by tillkamppeter** [comment]
Note that the new Snap packages are not yet available in the Store as the review and interface auto-connection request are still in progress. As the Store's build service is attached to the GitHub repo now, building on armhf is tested and succeeding now.
